version: ' 3'
services:
 www:
    build:
     context : .  # this for the doccker cofg
     dockerfile: Dockerfile
    #image: php:apache
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
   
 db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=cloud_project
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=docker # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops  

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=330